title: Ceilifreelance
description: Ceilifreelance site
theme: jekyll-theme-primer

source: .  # <-- Or uncomment and set to '.'

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata

sass:
  style: compressed

exclude:
  - node_modules
