title: Ceilifreelance
description: Ceilifreelance site
theme: jekyll-theme-primer

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata

sass:
  sass_dir: assets/css
  style: compressed

exclude:
  - node_modules
