# Basic Jekyll configuration
title: Ceilifreelance
description: Ceilifreelance site
theme: jekyll-theme-primer

# Specify source and destination if needed, or leave as default
# destination: _site

# Plugins example, add as needed
plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata

# Defaults for asset handling
sass:
  style: compressed

# Exclude files/folders from build
exclude:
  - node_modules
